docs: add terraform files to deploy a vmware cluster
spectrocloud/tutorials pull request #36
Opened 2024-02-15 21:46 UTC by caroldelwing

## Describe the Change

This PR adds the Terraform files required to deploy a VMware cluster profile and cluster. The files will be used in the new PCG tutorial. 

(Work in progress, do not merge)

## Review Changes

🎫 [DOC-1049](https://spectrocloud.atlassian.net/browse/DOC-1049)

2024-02-20 16:57 UTC, karl-cardenas-coding requested changes
Great start - I left some suggestions for we can improve the code and user experience. We also need to add an entry to the main README that links to this tutorial README.

2024-02-20 16:57 UTC, karl-cardenas-coding commented on terraform/vmware-cluster-deployment-tf/README.md
> +This folder contains the demo code for the Deploy App Workloads with a PCG tutorial. Use the code in this directory with the tutorial.
If you know what filename you will use, then you can include the markdown link to it.

2024-02-20 16:57 UTC, karl-cardenas-coding commented on terraform/vmware-cluster-deployment-tf/README.md
> +3. A public SSH key that will be used to access the cluster nodes.
We can create an SSH key for users to make their life easier and also give them the option to provide one. Check out how we do it in the `iaas-cluster-deployment` code :)

2024-02-20 16:57 UTC, karl-cardenas-coding commented on terraform/vmware-cluster-deployment-tf/inputs.tf
> +  default = ["spectro-cloud-education", "app:hello-universe", "terraform_managed:true"]
Let's also add  `"repository:spectrocloud:tutorials"` and `"tutorial:TUTORIAL_NAME_HERE"`

2024-02-20 16:57 UTC, karl-cardenas-coding commented on terraform/vmware-cluster-deployment-tf/data.tf
> +  version      = "0.13.7"
```suggestion
  version      = "0.13.11"
```
We should use the new Helm version as the old non-Helm is not gonna be supported moving forward.

2024-02-20 16:57 UTC, karl-cardenas-coding commented on terraform/vmware-cluster-deployment-tf/profile.tf
> +    values = format("%s      - %s", data.spectrocloud_pack.metallb.values, var.metallb_ip)
In the new Helm pack, the value is in the following block. Maybe the better option is to use `format` on the default IP?

```yaml
charts:
  metallb-full:
    configuration:
      ipaddresspools:
        first-pool:
          spec:
            addresses:
              - 192.168.10.0/24
              # - 192.168.100.50-192.168.100.60
            avoidBuggyIPs: true
            autoAssign: true

```

2024-02-21 17:56 UTC, caroldelwing commented on terraform/vmware-cluster-deployment-tf/inputs.tf
> +  default = ["spectro-cloud-education", "app:hello-universe", "terraform_managed:true"]
:white_check_mark:

2024-02-21 18:02 UTC, caroldelwing commented on terraform/vmware-cluster-deployment-tf/profile.tf
> +    values = format("%s      - %s", data.spectrocloud_pack.metallb.values, var.metallb_ip)
I have updated the code to use the Helm pack and have utilized the 'replace' function since the addresses line is placed in the middle of the file.

2024-02-21 19:59 UTC, caroldelwing commented on terraform/vmware-cluster-deployment-tf/README.md
> +3. A public SSH key that will be used to access the cluster nodes.
:white_check_mark:

2024-02-21 19:59 UTC, caroldelwing commented on terraform/vmware-cluster-deployment-tf/data.tf
> +  version      = "0.13.7"
Updated :)

2024-03-01 15:08 UTC, karl-cardenas-coding approved these changes
Looks great 🚀

2024-03-01 15:08 UTC, karl-cardenas-coding commented on terraform/vmware-cluster-deployment-tf/provider.tf
> +      version = ">= 0.16.1"
```suggestion
      version = ">= 0.17.4"
```
17.4 is the latest

2024-03-01 15:15 UTC, merged