fix: add terraform files for the getting started tutorial
spectrocloud/tutorials pull request #39
Opened 2024-05-31 21:15 UTC by caroldelwing

## Describe the Change

This PR adds the Terraform files required for the new Terraform Getting Started tutorials. 
The tutorials will cover how to deploy and update a cluster to AWS, Azure, GCP, and VMware vSphere.

Note: this PR will be merged when the tutorials are ready.

## Review Changes

🎫 [DOC-1200](https://spectrocloud.atlassian.net/browse/DOC-1200)

2024-06-03 15:35 UTC, karl-cardenas-coding requested changes
Really nice start. I left some suggestion below

2024-06-03 15:35 UTC, karl-cardenas-coding commented on terraform/getting-started-deployment-tf/clusters.tf
> +    #id = spectrocloud_cluster_profile.aws-profile-new[0].id
```suggestion
```

2024-06-03 15:35 UTC, karl-cardenas-coding commented on terraform/getting-started-deployment-tf/clusters.tf
> +    #id = spectrocloud_cluster_profile.azure-profile[0].id
```suggestion
```

2024-06-03 15:35 UTC, karl-cardenas-coding commented on terraform/getting-started-deployment-tf/clusters.tf
> +    #id = spectrocloud_cluster_profile.gcp-profile-new[0].id
```suggestion
```

2024-06-03 15:35 UTC, karl-cardenas-coding commented on terraform/getting-started-deployment-tf/clusters.tf
> +    #id = spectrocloud_cluster_profile.vmware-profile-new[0].id
```suggestion
```

2024-06-03 15:35 UTC, karl-cardenas-coding commented on terraform/getting-started-deployment-tf/cluster_profiles.tf
> +      auth_token  = var.auth_token
@caroldelwing we could use the [base64 function](https://developer.hashicorp.com/terraform/language/functions/base64encode) here so that the user does not have to do that themselves :) t

2024-06-03 15:35 UTC, karl-cardenas-coding commented on terraform/getting-started-deployment-tf/terraform.tfvars
> +auth_token      = "REPLACE ME"     # The base64 encoded auth token for the API connection.
I left a comment in the cluster_profile.tf but we can take care of the base64 encoding.

2024-06-03 15:35 UTC, karl-cardenas-coding commented on terraform/getting-started-deployment-tf/inputs.tf
> +}
@caroldelwing let's make these variables [sensitive](https://developer.hashicorp.com/terraform/tutorials/configuration-language/sensitive-variables)

2024-06-03 15:35 UTC, karl-cardenas-coding commented on terraform/getting-started-deployment-tf/inputs.tf
> +variable "deploy-vmware-new" {
Maybe we can use a better variable name?

2024-06-03 15:35 UTC, karl-cardenas-coding commented on terraform/getting-started-deployment-tf/ippool.tf
> +# }
@caroldelwing we don't have to comment this out, you could use a variable that creates the resource or not based on a value and using count. For example

```hcl
var.deploy-pcg-with-ip-pool ? 1: 0
```

2024-06-03 15:35 UTC, karl-cardenas-coding commented on terraform/getting-started-deployment-tf/provider.tf
> +  project_name = "Default"
Let's make this a variable but with a default value :)

2024-06-03 15:35 UTC, karl-cardenas-coding commented on terraform/getting-started-deployment-tf/ssh-key.tf
> +resource "local_sensitive_file" "private_key_file" {
Nicely done using local_sensitive_file

2024-06-13 16:10 UTC, caroldelwing commented on terraform/getting-started-deployment-tf/inputs.tf
> +variable "deploy-vmware-new" {
:white_check_mark:

2024-06-13 18:41 UTC, caroldelwing commented on terraform/getting-started-deployment-tf/clusters.tf
> +    #id = spectrocloud_cluster_profile.aws-profile-new[0].id
:white_check_mark:

2024-06-13 18:41 UTC, caroldelwing commented on terraform/getting-started-deployment-tf/clusters.tf
> +    #id = spectrocloud_cluster_profile.azure-profile[0].id
:white_check_mark:

2024-06-13 18:41 UTC, caroldelwing commented on terraform/getting-started-deployment-tf/clusters.tf
> +    #id = spectrocloud_cluster_profile.vmware-profile-new[0].id
:white_check_mark:

2024-06-13 18:41 UTC, caroldelwing commented on terraform/getting-started-deployment-tf/clusters.tf
> +    #id = spectrocloud_cluster_profile.gcp-profile-new[0].id
:white_check_mark:

2024-06-13 18:42 UTC, caroldelwing commented on terraform/getting-started-deployment-tf/terraform.tfvars
> +auth_token      = "REPLACE ME"     # The base64 encoded auth token for the API connection.
:white_check_mark:

2024-06-13 18:49 UTC, caroldelwing commented on terraform/getting-started-deployment-tf/cluster_profiles.tf
> +      auth_token  = var.auth_token
:white_check_mark:

2024-06-13 18:51 UTC, caroldelwing commented on terraform/getting-started-deployment-tf/inputs.tf
> +}
:white_check_mark:

2024-06-14 20:37 UTC, caroldelwing commented on terraform/getting-started-deployment-tf/ippool.tf
> +# }
:white_check_mark:

2024-07-02 18:04 UTC, karl-cardenas-coding approved these changes
Approved

2024-07-02 18:04 UTC, karl-cardenas-coding commented on Dockerfile
> +        wget https://github.com/derailed/k9s/releases/download/v0.32.5/k9s_Linux_amd64.tar.gz -O - | tar -xz -C /usr/local/bin && \
Let's variabilize the version like we do with other assets

2024-07-02 18:07 UTC, addetz approved these changes
Wonderful work 👏

2024-07-02 18:10 UTC, addetz commented on terraform/getting-started-deployment-tf/README.md
> +- [Cluster Management with Terraform - VMware](https://docs.spectrocloud.com/getting-started/vmware/manage-cluster-tf)
Suggest not writing these links in, as we will only merge into master once Phase 2 completes.

2024-07-02 19:43 UTC, caroldelwing commented on terraform/getting-started-deployment-tf/README.md
> +- [Cluster Management with Terraform - VMware](https://docs.spectrocloud.com/getting-started/vmware/manage-cluster-tf)
Sure :) I will comment these out and then add them back later.

2024-07-02 19:44 UTC, caroldelwing commented on Dockerfile
> +        wget https://github.com/derailed/k9s/releases/download/v0.32.5/k9s_Linux_amd64.tar.gz -O - | tar -xz -C /usr/local/bin && \
Oh, good point! Will do.

2024-09-23 13:54 UTC, merged